#spring:
#  config:
#    import: configserver:${CONFIG_URL:http://localhost:8800}/
#  application:
#    name: minio
#  cloud:
#    config:
#      name: ${spring.application.name}
#      uri: ${CONFIG_URL}
#      fail-fast: true
#      retry:
#        initial-interval: 2000
#        max-interval: 10000
#        multiplier: 2
#        max-attempts: 10
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka/}
server:
  port: 8089

minio:
  endpoint: http://minio:9000
  accessKey: FGa09cfnVLkDc6frnge7
  secretKey: Hh4aTTUVES6i0RKsgHOk7V6URZryMWLHUDydQRhA
  bucket: filesdemo

spring:
  kafka:
    bootstrap-servers: kafka1:9093,kafka2:9095,kafka3:9097
    consumer:
      group-id: minio-group
      minio-group: minio-group
      auto-offset-reset: earliest
