server:
  port: 8089

springdoc:
  swagger-ui.path: /api/minio/docs/swagger-ui
  api-docs.path: /api/minio/docs/v3/api-docs

minio:
  endpoint: http://minio:9000
  accessKey: FGa09cfnVLkDc6frnge7
  secretKey: Hh4aTTUVES6i0RKsgHOk7V6URZryMWLHUDydQRhA
  bucket: filesdemo

spring:
  kafka:
    bootstrap-servers: kafka1:9093,kafka2:9095,kafka3:9097
    consumer:
      group-id: minio-group
      minio-group: minio-group
      auto-offset-reset: earliest
