server:
  port: '8888'
  servlet:
    context-path: /
spring:
  application:
    name: analysis
    page-size: '5'
  config:
    import: classpath:email-config.properties
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
  devtools:
    restart:
      enabled: 'true'
  flyway:
    baselineOnMigrate: 'true'
    enabled: 'true'
    locations: classpath:db/migration,classpath:/db/testmigration
    schemas: public
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'
springdoc:
  swagger-ui.path: /api/analyses/docs/swagger-ui
  api-docs.path: /api/analyses/docs/v3/api-docs
