spring:
  application:
    name: billing
    page-size: 5
  devtools.restart.enabled: true
  jackson.property-naming-strategy: SNAKE_CASE

springdoc:
  swagger-ui.path: /api/billing/docs/swagger-ui
  api-docs.path: /api/billing/docs/v3/api-docs

server:
  port: 8888
  servlet.context-path: /

patient.service.url: http://patient:8888/api/patients/
appointment.service.url: http://appointment:8888/api/appointments/