server:
  port: '8888'
  servlet:
    context-path: /
spring:
  application:
    name: doctor
    page-size: '5'
  devtools:
    restart:
      enabled: 'true'
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}
    password: ${DB_PASSWORD:1234}
    username: ${DB_USER:postgres}
  data:
    r2dbc:
      repositories:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}
    password: ${DB_PASSWORD:1234}
    username: ${DB_USER:postgres}
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}
    baselineOnMigrate: 'true'
    enabled: 'true'
    locations: classpath:db/migration,classpath:/db/testmigration
    schemas: public
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'

springdoc:
  swagger-ui.path: /api/doctors/docs/swagger-ui
  api-docs.path: /api/doctors/docs/v3/api-docs

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka/}