spring:
  application:
    name: mail
    page-size: 5
  devtools.restart.enabled: true
  jackson.property-naming-strategy: SNAKE_CASE

springdoc:
  swagger-ui.path: /api/mail/docs/swagger-ui
  api-docs.path: /api/mail/docs/v3/api-docs

server:
  port: 8888
  servlet.context-path: /

email:
  sender: ilya.minyaeff@yandex.ru
  host: smtp.yandex.ru
  port: 465
  password: dyrdtgkrhajjptlh