#spring:
#  application:
#    name: minio
#  cloud:
#    config:
#      name: ${spring.application.name}
#      uri: ${CONFIG_URL}
#      fail-fast: true
#      retry:
#        initial-interval: 2000
#        max-interval: 10000
#        multiplier: 2
#        max-attempts: 10
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka/}
#
#minio:
#  endpoint: http://minio:9000
#  accessKey: FGa09cfnVLkDc6frnge7
#  secretKey: Hh4aTTUVES6i0RKsgHOk7V6URZryMWLHUDydQRhA
#  bucket: filesdemo
#
#server:
#  port: 8888
#  servlet.context-path: /
#
##doctor.service.url: ${DOCTOR_SERVICE:http://doctor:8888/api/doctors}
##patient.service.url: ${PATIENT_SERVICE:http://patient:8888/api/patients}
##mail.service.url: ${MAIL_SERVICE:http://mail:8888/api/mail}
#
#
