spring:
  application:
    name: recipe
    page-size: 5
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:1234}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
  flyway:
    locations: classpath:db/migration,classpath:/db/testmigration

springdoc:
  swagger-ui.path: /api/recipes/docs/swagger-ui
  api-docs.path: /api/recipes/docs/v3/api-docs