spring:
  application:
    name: timetable
    page-size: 5
  devtools.restart.enabled: true
  jackson.property-naming-strategy: SNAKE_CASE

springdoc:
  swagger-ui.path: /api/timetable/docs/swagger-ui
  api-docs.path: /api/timetable/docs/v3/api-docs

server:
  port: 8888
  servlet.context-path: /

appointment.service.url: http://appointment:8888/api/appointments