spring:
  config:
    import: configserver:${CONFIG_URL:http://localhost:8800}/
  application:
    name: auth
  cloud:
    config:
      name: ${spring.application.name}
      uri: ${CONFIG_URL}
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 10

  kafka:
    bootstrap-servers: kafka1:9093,kafka2:9095,kafka3:9097
    consumer:
      group-id: auth-group
      auth-group: auth-group
      auto-offset-reset: earliest


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
